import { StyleSheet } from 'react-native';
import { colors, colorCombinations } from '../constants/colors';

export const homeScreenStyles = StyleSheet.create({
  fullScreenContainer: {
    flex: 1,
    backgroundColor: colors.backBlack,
  },
  fullScreenMap: {
    flex: 1,
  },
  headerOverlay: {
    position: 'absolute',
    left: 0,
    right: 0,
    paddingHorizontal: 20,
    zIndex: 1000,
  },
  headerContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 12,
  },
  modernButton: {
    width: 60,
    height: 60,
    borderRadius: 30,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: colors.surfaceGrey,
    borderWidth: 1,
    borderColor: colors.outlineGrey,
    shadowColor: colors.primary,
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.3,
    shadowRadius: 16,
    elevation: 12,
  },
  profileButtonHeader: {
    backgroundColor: colors.surfaceGrey,
    shadowColor: colors.primary,
    padding: 2,
    width: 60,
    height: 60,
    borderRadius: 30,
    borderWidth: 1,
    borderColor: colors.primary,
  },
  profileImageContainer: {
    width: '100%',
    height: '100%',
    borderRadius: 23,
    justifyContent: 'center',
    alignItems: 'center',
    overflow: 'hidden',
  },
  profileAvatar: {
    width: 56,
    height: 56,
    borderRadius: 12,
    borderWidth: 2,
    borderColor: colors.primary,
    backgroundColor: colors.surfaceGrey,
    shadowColor: colors.primary,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.4,
    shadowRadius: 8,
    elevation: 8,
  },
  friendRequestButton: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: 'transparent', // arka plan kaldırıldı
    borderWidth: 0,
    shadowColor: colors.secondary,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.25,
    shadowRadius: 8, // daha yumuşak gölge
    elevation: 8,
  },
  friendRequestIcon: {
    width: 40,
    height: 40,
  },
  buttonGlow: {
    width: '100%',
    height: '100%',
    borderRadius: 30,
    justifyContent: 'center',
    alignItems: 'center',
    position: 'relative',
  },
  notificationBadge: {
    position: 'absolute',
    top: -4,
    right: -4,
    backgroundColor: colors.secondary,
    borderRadius: 12,
    minWidth: 24,
    height: 24,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 2,
    borderColor: colors.surfaceGrey,
    shadowColor: colors.secondary,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.4,
    shadowRadius: 6,
    elevation: 6,
  },
  badgeText: {
    color: colors.textPrimary,
    fontSize: 12,
    fontWeight: 'bold',
    textAlign: 'center',
  },
  logoContainer: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  overlayLogo: {
    width: 120,
    height: 60,
    backgroundColor: colors.surfaceGrey,
    borderRadius: 24,
    paddingHorizontal: 16,
    paddingVertical: 8,
    shadowColor: colors.primary,
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.3,
    shadowRadius: 20,
    elevation: 16,
    borderWidth: 1,
    borderColor: colors.outlineGrey,
  },
  locationButtonContainer: {
    position: 'absolute',
    bottom: 100,
    right: 16, // sağ kenara 16px boşluk
    zIndex: 1000,
  },
  locationButton: {
    width: 52,
    height: 52,
    borderRadius: 26,
    backgroundColor: 'transparent', // zemin kaldırıldı
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: colors.primary, // ikonla aynı neon gölgesi
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.4,
    shadowRadius: 10,
    elevation: 10,
  },
  locationIcon: {
    width: 30,
    height: 30,
  },
  
  // Modern Animated FAB Styles - Neon Gradient
  fabContainer: {
    position: 'absolute',
    bottom: 120,
    alignSelf: 'center',
    width: 70,
    height: 70,
    zIndex: 1001,
  },
  fabTouchable: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  fabButton: {
    width: 60,
    height: 60,
    borderRadius: 30,
    backgroundColor: colors.primary,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: colors.primary,
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.5,
    shadowRadius: 20,
    elevation: 15,
    borderWidth: 2,
    borderColor: colors.secondary,
    zIndex: 4,
  },
  fabGlowOuter: {
    position: 'absolute',
    width: 70,
    height: 70,
    borderRadius: 35,
    backgroundColor: 'transparent',
    borderWidth: 1,
    borderColor: colors.primary,
    opacity: 0.4,
    zIndex: 1,
  },
  fabGlowMiddle: {
    position: 'absolute',
    width: 66,
    height: 66,
    borderRadius: 33,
    backgroundColor: colors.primary,
    opacity: 0.08,
    zIndex: 2,
  },
  fabGlowInner: {
    position: 'absolute',
    width: 62,
    height: 62,
    borderRadius: 31,
    backgroundColor: colors.primary,
    opacity: 0.15,
    zIndex: 3,
  },
  mapDarkOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: '#000000',
    opacity: 0.1,
    zIndex: 1,
    pointerEvents: 'none',
  },
  appleLogoOverlay: {
    position: 'absolute',
    bottom: 35,
    left: -0,
    width: 40,
    height: 40,
    zIndex: 2000,
    transform: [{ rotate: '270deg' }],
  },
}); 